### ISSUE TITLE
signing of the logout request messages is mandatory (currently is optional)

### ISSUE THREAD

**Issue by siacomuzzi** [auth0/samlp-logout#2]
http://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf (section 4.4.3.1):

```
The <LogoutRequest> message MUST be signed if the HTTP POST or Redirect binding is used.
```

**Comment by markstuart** [comment]
This looks to have been completed? One possible enhancement would be to add the `identityProviderSigningCert` 'option' to the example in the README, since it is also required.

**Comment by siacomuzzi** [comment]
Yes, its completed (regular SLO and idp initiated SLO flows).

I just updated the README with your suggestion: https://github.com/auth0/samlp-logout/blob/master/README.md#usage

Thanks for the feedback!
